export const APLICATIVOS_CREATE = "APLICATIVOS_CREATE";
export const APLICATIVOS_UPDATE = "APLICATIVOS_UPDATE";
export const APLICATIVOS_DELETE = "APLICATIVOS_DELETE";

export const PROVINCIAS_CREATE = "PROVINCIAS_CREATE";
export const PROVINCIAS_UPDATE = "PROVINCIAS_UPDATE";
export const PROVINCIAS_DELETE = "PROVINCIAS_DELETE";

export const CONDICIONES_FISCALES_CREATE = "CONDICIONES_FISCALES_CREATE";
export const CONDICIONES_FISCALES_UPDATE = "CONDICIONES_FISCALES_UPDATE";
export const CONDICIONES_FISCALES_DELETE = "CONDICIONES_FISCALES_DELETE";

export const TIPOS_DE_PERSONA_CREATE = "TIPOS_DE_PERSONA_CREATE";
export const TIPOS_DE_PERSONA_UPDATE = "TIPOS_DE_PERSONA_UPDATE";
export const TIPOS_DE_PERSONA_DELETE = "TIPOS_DE_PERSONA_DELETE";

export const PRODUCTOS_CREATE = 'PRODUCTOS_CREATE';
export const PRODUCTOS_UPDATE = 'PRODUCTOS_UPDATE';
export const PRODUCTOS_DELETE = 'PRODUCTOS_DELETE';

export const IMPUESTOS_CREATE = 'IMPUESTOS_CREATE';
export const IMPUESTOS_UPDATE = 'IMPUESTOS_UPDATE';
export const IMPUESTOS_DELETE = 'IMPUESTOS_DELETE';

export const TRANSACCION_CREATE = 'TRANSACCION_CREATE';
export const TRANSACCION_UPDATE = 'TRANSACCION_UPDATE';
export const TRANSACCION_DELETE = 'TRANSACCION_DELETE';


export const REGIMEN_IMPOSITIVO_CREATE = "REGIMEN_IMPOSITIVO_CREATE";
export const REGIMEN_IMPOSITIVO_UPDATE = "REGIMEN_IMPOSITIVO_UPDATE";

export const ADD_EDIT_SUCCESS = "ADD_EDIT_SUCCESS";

export const VER_DETALLE = "VER_DETALLE";
